apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-4-tenant/load-app-309cbbbc-f262-4beb-8edf-5ce27bbc2353/devfile-sample@sha256:4f87e92e7b843bb525d906e0b28c12a852e83fc28edb9cd6af05c82a9810e6ed
        name: my-nodejs
        resources: {}
status: {}
